name: basic
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences:
  cupertino_icons: ^0.1.2
  json_table: ^1.2.0
  intl: ^0.15.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/json/data.json
    - assets/json/